### ISSUE TITLE
How to use it with v-for directive?

### ISSUE THREAD

**Issue by berlaga** [termosa/vue-uniq-ids#3]
Looks like in case of v-for, all repeated items get same id. What am I doing wrong?
Thanks,
Alex

**Comment by termosa** [comment]
Hi @berlaga!
I didn't actually think of it. Did you find a solution?

**Comment by termosa** [comment]
You can use item specific value to make those IDs unique again:
```
<li v-for="user in users" v-uni-id="user.id"> ... </li>
```
